/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.fatesg.pizzaria.view;

import br.com.fatesg.pizzaria.decorator.*;
import br.com.fatesg.pizzaria.factory.*;
import br.com.fatesg.pizzaria.models.*;
import br.com.fatesg.pizzaria.services.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaCardapio extends javax.swing.JFrame {

    private Usuario usuarioLogado;
    /**
     * Creates new form TelaCardapio
     */
    private List<PedidoItem> carrinho = new ArrayList<>();

    public TelaCardapio(Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBoxPizzas = new javax.swing.JComboBox<>();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxCebola = new javax.swing.JCheckBox();
        jCheckBoxAbacaxi = new javax.swing.JCheckBox();
        jCheckBoxBacon = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxPizzas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CALABRESA", "MARGUERITA", "MUSSARELA" }));
        getContentPane().add(jComboBoxPizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 101, 120, -1));
        getContentPane().add(jTextFieldQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 101, 100, -1));

        jLabel1.setText("QUANTIDADE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 79, -1, -1));

        jLabel2.setText("SELECIONE SUA PIZZA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 79, -1, -1));

        jCheckBoxCebola.setText("CEBOLA");
        getContentPane().add(jCheckBoxCebola, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 85, -1));

        jCheckBoxAbacaxi.setText("ABACAXI");
        getContentPane().add(jCheckBoxAbacaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 85, -1));

        jCheckBoxBacon.setText("BACON");
        getContentPane().add(jCheckBoxBacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 85, -1));

        jLabel3.setText("ADICIONAIS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jButtonFinalizar.setText("FINALIZAR PEDIDO");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jButtonAdicionar.setText("ADICIONAR AO CARRINHO");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        String selectedPizza = (String) jComboBoxPizzas.getSelectedItem();

        List<Adicionais> adicionais = new ArrayList<>();

        int quantidade = 0;
        try {
            quantidade = Integer.parseInt(jTextFieldQuantidade.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Quantidade inválida.");
            return;
        }

        FabricaPizza.TipoPizza tipoPizza = FabricaPizza.TipoPizza.valueOf(selectedPizza.toUpperCase());
        Pizza pizza = new FabricaPizza().criarPizza(tipoPizza);

        if (jCheckBoxAbacaxi.isSelected()) {
            pizza = new Abacaxi(pizza);
        }
        if (jCheckBoxBacon.isSelected()) {
            pizza = new Bacon(pizza);
        }
        if (jCheckBoxCebola.isSelected()) {
            pizza = new Cebola(pizza);
        }

        PedidoItem item = new PedidoItem(pizza, quantidade);

        carrinho.add(item);

        jComboBoxPizzas.setSelectedIndex(0);
        jCheckBoxAbacaxi.setSelected(false);
        jCheckBoxBacon.setSelected(false);
        jCheckBoxCebola.setSelected(false);
        jTextFieldQuantidade.setText("");

        JOptionPane.showMessageDialog(null, "Pizza adicionada ao carrinho.");
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        // TODO add your handling code here:
        StringBuilder resumoCarrinho = new StringBuilder("Resumo do Carrinho:\n\n");
        double valorTotal = 0.0;

        for (PedidoItem pedidoItem : carrinho) {
            Pizza pizza = pedidoItem.getPizza();
            int quantidade = pedidoItem.getQuantidade();

            double valorItem = pizza.cost() * quantidade;
            valorTotal += valorItem;

            resumoCarrinho.append("Pizza: ").append(pizza.getDescription());
            resumoCarrinho.append(" (Quantidade: ").append(quantidade).append(")\n");
            resumoCarrinho.append("Valor do Item: R$").append(valorItem).append("\n\n");
        }

        resumoCarrinho.append("Valor Total do Pedido: R$").append(valorTotal);
        JOptionPane.showMessageDialog(null, resumoCarrinho.toString());

//        try {
//            Document document = new Document();
//            PdfWriter.getInstance(document, new FileOutputStream("resumo_pedido.pdf"));
//            document.open();
//            document.add(new Paragraph(resumoCarrinho.toString()));
//            document.close();
//            JOptionPane.showMessageDialog(null, "Resumo do pedido salvo em resumo_pedido.pdf.");
//        } catch (DocumentException | FileNotFoundException e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(null, "Erro ao salvar o resumo do pedido em PDF.");
//        }

        carrinho.clear();

        String descricaoPedido = resumoCarrinho.toString();

        int usuarioId = this.usuarioLogado.getId();

        PedidoService.inserirPedido(usuarioId, descricaoPedido, valorTotal);
        this.dispose();
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaCardapio(usuarioLogado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JCheckBox jCheckBoxAbacaxi;
    private javax.swing.JCheckBox jCheckBoxBacon;
    private javax.swing.JCheckBox jCheckBoxCebola;
    private javax.swing.JComboBox<String> jComboBoxPizzas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
